### ISSUE TITLE
Creating authors from API results in displayName being set as an object

### ISSUE THREAD

**Issue by benetherington** [benetherington/node-TOM-discord-bot#29]
We get `[object Object]` for displayName. This is probably an issue in `/interface/title-interface.js:20`.

**Comment by benetherington** [comment]
```js
{"level":50,"time":1649004433714,"pid":808,"hostname":"76b68bb4b938","reqId":"req-u","err":{"type":"JsonWebTokenError","message":"jwt must be provided","stack":"JsonWebTokenError: jwt must be provided\n    at Object.module.exports [as verify] (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/jsonwebtoken/verify.js:53:17)\n    at verifyToken (/app/src/sqlite/admin.js:94:30)\n    at module.exports.getAdminByToken (/app/src/sqlite/admin.js:120:19)\n    at module.exports.getAdminFromTokenOrRedirect (/app/src/routes/loginUtilities.js:9:25)\n    at Object.<anonymous> (/app/src/routes/monitor.js:13:29)\n    at preHandlerCallback (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/handleRequest.js:109:5)\n    at handler (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/handleRequest.js:72:7)\n    at handleRequest (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/handleRequest.js:20:5)\n    at runPreParsing (/rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/route.js:451:5)","name":"JsonWebTokenError"},"msg":"Promise errored, but reply.sent = true was set"}
Remove vote from CsabaT for <3>.
{"level":30,"time":1649004433799,"pid":808,"hostname":"76b68bb4b938","reqId":"req-v","req":{"method":"GET","url":"/login?auth=none","hostname":"tom-title-suggestion-monitor.glitch.me","remoteAddress":"127.0.0.1","remotePort":39874},"msg":"incoming request"}
{"level":50,"time":1649004433800,"pid":808,"hostname":"76b68bb4b938","reqId":"req-v","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /rbd/pnpm-volume/1c3f4846-cb24-4db9-9b9d-30d0fb6a0f60/node_modules/fastify/lib/wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
```

Might be throwing an additional error that fails out update requests
